-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity t_int is
generic (
    C_S_AXI_HLS_TREEADD_PERIPH_BUS_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_HLS_TREEADD_PERIPH_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_AWVALID : IN STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_HLS_TREEADD_PERIPH_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_HLS_TREEADD_PERIPH_BUS_WVALID : IN STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_WREADY : OUT STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_HLS_TREEADD_PERIPH_BUS_DATA_WIDTH-1 downto 0);
    s_axi_HLS_TREEADD_PERIPH_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_HLS_TREEADD_PERIPH_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_HLS_TREEADD_PERIPH_BUS_ARVALID : IN STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_HLS_TREEADD_PERIPH_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_HLS_TREEADD_PERIPH_BUS_RVALID : OUT STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_RREADY : IN STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_HLS_TREEADD_PERIPH_BUS_DATA_WIDTH-1 downto 0);
    s_axi_HLS_TREEADD_PERIPH_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_HLS_TREEADD_PERIPH_BUS_BVALID : OUT STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_BREADY : IN STD_LOGIC;
    s_axi_HLS_TREEADD_PERIPH_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of t_int is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "t_int_t_int,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.923000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=498,HLS_SYN_LUT=907,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal a : STD_LOGIC_VECTOR (31 downto 0);
    signal b : STD_LOGIC_VECTOR (31 downto 0);
    signal c : STD_LOGIC_VECTOR (31 downto 0);
    signal d : STD_LOGIC_VECTOR (31 downto 0);
    signal e : STD_LOGIC_VECTOR (31 downto 0);
    signal f : STD_LOGIC_VECTOR (31 downto 0);
    signal g : STD_LOGIC_VECTOR (31 downto 0);
    signal h : STD_LOGIC_VECTOR (31 downto 0);
    signal r : STD_LOGIC_VECTOR (31 downto 0);
    signal r_ap_vld : STD_LOGIC;
    signal done_ap_vld : STD_LOGIC;
    signal add_ln43_fu_133_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_reg_173 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_1_fu_139_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_1_reg_178 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_5_fu_157_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_5_reg_183 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln43_4_fu_151_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_3_fu_145_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_2_fu_163_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component t_int_HLS_TREEADD_PERIPH_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        a : OUT STD_LOGIC_VECTOR (31 downto 0);
        b : OUT STD_LOGIC_VECTOR (31 downto 0);
        c : OUT STD_LOGIC_VECTOR (31 downto 0);
        d : OUT STD_LOGIC_VECTOR (31 downto 0);
        e : OUT STD_LOGIC_VECTOR (31 downto 0);
        f : OUT STD_LOGIC_VECTOR (31 downto 0);
        g : OUT STD_LOGIC_VECTOR (31 downto 0);
        h : OUT STD_LOGIC_VECTOR (31 downto 0);
        r : IN STD_LOGIC_VECTOR (31 downto 0);
        r_ap_vld : IN STD_LOGIC;
        done : IN STD_LOGIC_VECTOR (15 downto 0);
        done_ap_vld : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    HLS_TREEADD_PERIPH_BUS_s_axi_U : component t_int_HLS_TREEADD_PERIPH_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_HLS_TREEADD_PERIPH_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_HLS_TREEADD_PERIPH_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_HLS_TREEADD_PERIPH_BUS_AWVALID,
        AWREADY => s_axi_HLS_TREEADD_PERIPH_BUS_AWREADY,
        AWADDR => s_axi_HLS_TREEADD_PERIPH_BUS_AWADDR,
        WVALID => s_axi_HLS_TREEADD_PERIPH_BUS_WVALID,
        WREADY => s_axi_HLS_TREEADD_PERIPH_BUS_WREADY,
        WDATA => s_axi_HLS_TREEADD_PERIPH_BUS_WDATA,
        WSTRB => s_axi_HLS_TREEADD_PERIPH_BUS_WSTRB,
        ARVALID => s_axi_HLS_TREEADD_PERIPH_BUS_ARVALID,
        ARREADY => s_axi_HLS_TREEADD_PERIPH_BUS_ARREADY,
        ARADDR => s_axi_HLS_TREEADD_PERIPH_BUS_ARADDR,
        RVALID => s_axi_HLS_TREEADD_PERIPH_BUS_RVALID,
        RREADY => s_axi_HLS_TREEADD_PERIPH_BUS_RREADY,
        RDATA => s_axi_HLS_TREEADD_PERIPH_BUS_RDATA,
        RRESP => s_axi_HLS_TREEADD_PERIPH_BUS_RRESP,
        BVALID => s_axi_HLS_TREEADD_PERIPH_BUS_BVALID,
        BREADY => s_axi_HLS_TREEADD_PERIPH_BUS_BREADY,
        BRESP => s_axi_HLS_TREEADD_PERIPH_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        a => a,
        b => b,
        c => c,
        d => d,
        e => e,
        f => f,
        g => g,
        h => h,
        r => r,
        r_ap_vld => r_ap_vld,
        done => ap_const_lv16_1,
        done_ap_vld => done_ap_vld,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln43_1_reg_178 <= add_ln43_1_fu_139_p2;
                add_ln43_5_reg_183 <= add_ln43_5_fu_157_p2;
                add_ln43_reg_173 <= add_ln43_fu_133_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln43_1_fu_139_p2 <= std_logic_vector(unsigned(c) + unsigned(d));
    add_ln43_2_fu_163_p2 <= std_logic_vector(unsigned(add_ln43_1_reg_178) + unsigned(add_ln43_reg_173));
    add_ln43_3_fu_145_p2 <= std_logic_vector(unsigned(e) + unsigned(f));
    add_ln43_4_fu_151_p2 <= std_logic_vector(unsigned(g) + unsigned(h));
    add_ln43_5_fu_157_p2 <= std_logic_vector(unsigned(add_ln43_4_fu_151_p2) + unsigned(add_ln43_3_fu_145_p2));
    add_ln43_fu_133_p2 <= std_logic_vector(unsigned(b) + unsigned(a));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    done_ap_vld_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            done_ap_vld <= ap_const_logic_1;
        else 
            done_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r <= std_logic_vector(unsigned(add_ln43_5_reg_183) + unsigned(add_ln43_2_fu_163_p2));

    r_ap_vld_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            r_ap_vld <= ap_const_logic_1;
        else 
            r_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
