# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/ELEC_522/FpgaEx/Fpga_hls/hls_component_lreg/linear_model/hls/impl/verilog/linear_model.xdc

# Block Designs: bd/bd_0/bd_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0} -quiet] -quiet

# IP: bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0_hls_inst_0 || ORIG_REF_NAME==bd_0_hls_inst_0} -quiet] -quiet

# XDC: d:/ELEC_522/FpgaEx/Fpga_hls/hls_component_lreg/linear_model/hls/impl/verilog/project.gen/sources_1/bd/bd_0/bd_0_ooc.xdc
