// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="t_int_t_int,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.923000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=498,HLS_SYN_LUT=907,HLS_VERSION=2025_1}" *)

module t_int (
        ap_clk,
        ap_rst_n,
        s_axi_HLS_TREEADD_PERIPH_BUS_AWVALID,
        s_axi_HLS_TREEADD_PERIPH_BUS_AWREADY,
        s_axi_HLS_TREEADD_PERIPH_BUS_AWADDR,
        s_axi_HLS_TREEADD_PERIPH_BUS_WVALID,
        s_axi_HLS_TREEADD_PERIPH_BUS_WREADY,
        s_axi_HLS_TREEADD_PERIPH_BUS_WDATA,
        s_axi_HLS_TREEADD_PERIPH_BUS_WSTRB,
        s_axi_HLS_TREEADD_PERIPH_BUS_ARVALID,
        s_axi_HLS_TREEADD_PERIPH_BUS_ARREADY,
        s_axi_HLS_TREEADD_PERIPH_BUS_ARADDR,
        s_axi_HLS_TREEADD_PERIPH_BUS_RVALID,
        s_axi_HLS_TREEADD_PERIPH_BUS_RREADY,
        s_axi_HLS_TREEADD_PERIPH_BUS_RDATA,
        s_axi_HLS_TREEADD_PERIPH_BUS_RRESP,
        s_axi_HLS_TREEADD_PERIPH_BUS_BVALID,
        s_axi_HLS_TREEADD_PERIPH_BUS_BREADY,
        s_axi_HLS_TREEADD_PERIPH_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_HLS_TREEADD_PERIPH_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_HLS_TREEADD_PERIPH_BUS_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_HLS_TREEADD_PERIPH_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_HLS_TREEADD_PERIPH_BUS_AWVALID;
output   s_axi_HLS_TREEADD_PERIPH_BUS_AWREADY;
input  [C_S_AXI_HLS_TREEADD_PERIPH_BUS_ADDR_WIDTH - 1:0] s_axi_HLS_TREEADD_PERIPH_BUS_AWADDR;
input   s_axi_HLS_TREEADD_PERIPH_BUS_WVALID;
output   s_axi_HLS_TREEADD_PERIPH_BUS_WREADY;
input  [C_S_AXI_HLS_TREEADD_PERIPH_BUS_DATA_WIDTH - 1:0] s_axi_HLS_TREEADD_PERIPH_BUS_WDATA;
input  [C_S_AXI_HLS_TREEADD_PERIPH_BUS_WSTRB_WIDTH - 1:0] s_axi_HLS_TREEADD_PERIPH_BUS_WSTRB;
input   s_axi_HLS_TREEADD_PERIPH_BUS_ARVALID;
output   s_axi_HLS_TREEADD_PERIPH_BUS_ARREADY;
input  [C_S_AXI_HLS_TREEADD_PERIPH_BUS_ADDR_WIDTH - 1:0] s_axi_HLS_TREEADD_PERIPH_BUS_ARADDR;
output   s_axi_HLS_TREEADD_PERIPH_BUS_RVALID;
input   s_axi_HLS_TREEADD_PERIPH_BUS_RREADY;
output  [C_S_AXI_HLS_TREEADD_PERIPH_BUS_DATA_WIDTH - 1:0] s_axi_HLS_TREEADD_PERIPH_BUS_RDATA;
output  [1:0] s_axi_HLS_TREEADD_PERIPH_BUS_RRESP;
output   s_axi_HLS_TREEADD_PERIPH_BUS_BVALID;
input   s_axi_HLS_TREEADD_PERIPH_BUS_BREADY;
output  [1:0] s_axi_HLS_TREEADD_PERIPH_BUS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] a;
wire   [31:0] b;
wire   [31:0] c;
wire   [31:0] d;
wire   [31:0] e;
wire   [31:0] f;
wire   [31:0] g;
wire   [31:0] h;
wire   [31:0] r;
reg    r_ap_vld;
reg    done_ap_vld;
wire   [31:0] add_ln43_fu_133_p2;
reg   [31:0] add_ln43_reg_173;
wire   [31:0] add_ln43_1_fu_139_p2;
reg   [31:0] add_ln43_1_reg_178;
wire   [31:0] add_ln43_5_fu_157_p2;
reg   [31:0] add_ln43_5_reg_183;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln43_4_fu_151_p2;
wire   [31:0] add_ln43_3_fu_145_p2;
wire   [31:0] add_ln43_2_fu_163_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

t_int_HLS_TREEADD_PERIPH_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_HLS_TREEADD_PERIPH_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_HLS_TREEADD_PERIPH_BUS_DATA_WIDTH ))
HLS_TREEADD_PERIPH_BUS_s_axi_U(
    .AWVALID(s_axi_HLS_TREEADD_PERIPH_BUS_AWVALID),
    .AWREADY(s_axi_HLS_TREEADD_PERIPH_BUS_AWREADY),
    .AWADDR(s_axi_HLS_TREEADD_PERIPH_BUS_AWADDR),
    .WVALID(s_axi_HLS_TREEADD_PERIPH_BUS_WVALID),
    .WREADY(s_axi_HLS_TREEADD_PERIPH_BUS_WREADY),
    .WDATA(s_axi_HLS_TREEADD_PERIPH_BUS_WDATA),
    .WSTRB(s_axi_HLS_TREEADD_PERIPH_BUS_WSTRB),
    .ARVALID(s_axi_HLS_TREEADD_PERIPH_BUS_ARVALID),
    .ARREADY(s_axi_HLS_TREEADD_PERIPH_BUS_ARREADY),
    .ARADDR(s_axi_HLS_TREEADD_PERIPH_BUS_ARADDR),
    .RVALID(s_axi_HLS_TREEADD_PERIPH_BUS_RVALID),
    .RREADY(s_axi_HLS_TREEADD_PERIPH_BUS_RREADY),
    .RDATA(s_axi_HLS_TREEADD_PERIPH_BUS_RDATA),
    .RRESP(s_axi_HLS_TREEADD_PERIPH_BUS_RRESP),
    .BVALID(s_axi_HLS_TREEADD_PERIPH_BUS_BVALID),
    .BREADY(s_axi_HLS_TREEADD_PERIPH_BUS_BREADY),
    .BRESP(s_axi_HLS_TREEADD_PERIPH_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .a(a),
    .b(b),
    .c(c),
    .d(d),
    .e(e),
    .f(f),
    .g(g),
    .h(h),
    .r(r),
    .r_ap_vld(r_ap_vld),
    .done(16'd1),
    .done_ap_vld(done_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln43_1_reg_178 <= add_ln43_1_fu_139_p2;
        add_ln43_5_reg_183 <= add_ln43_5_fu_157_p2;
        add_ln43_reg_173 <= add_ln43_fu_133_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        done_ap_vld = 1'b1;
    end else begin
        done_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_ap_vld = 1'b1;
    end else begin
        r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln43_1_fu_139_p2 = (c + d);

assign add_ln43_2_fu_163_p2 = (add_ln43_1_reg_178 + add_ln43_reg_173);

assign add_ln43_3_fu_145_p2 = (e + f);

assign add_ln43_4_fu_151_p2 = (g + h);

assign add_ln43_5_fu_157_p2 = (add_ln43_4_fu_151_p2 + add_ln43_3_fu_145_p2);

assign add_ln43_fu_133_p2 = (b + a);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign r = (add_ln43_5_reg_183 + add_ln43_2_fu_163_p2);

endmodule //t_int
