// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="linear_model_linear_model,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.912000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=442,HLS_SYN_LUT=437,HLS_VERSION=2025_1}" *)

module linear_model (
        ap_clk,
        ap_rst_n,
        s_axi_HLS_LINEAR_PERIPH_BUS_AWVALID,
        s_axi_HLS_LINEAR_PERIPH_BUS_AWREADY,
        s_axi_HLS_LINEAR_PERIPH_BUS_AWADDR,
        s_axi_HLS_LINEAR_PERIPH_BUS_WVALID,
        s_axi_HLS_LINEAR_PERIPH_BUS_WREADY,
        s_axi_HLS_LINEAR_PERIPH_BUS_WDATA,
        s_axi_HLS_LINEAR_PERIPH_BUS_WSTRB,
        s_axi_HLS_LINEAR_PERIPH_BUS_ARVALID,
        s_axi_HLS_LINEAR_PERIPH_BUS_ARREADY,
        s_axi_HLS_LINEAR_PERIPH_BUS_ARADDR,
        s_axi_HLS_LINEAR_PERIPH_BUS_RVALID,
        s_axi_HLS_LINEAR_PERIPH_BUS_RREADY,
        s_axi_HLS_LINEAR_PERIPH_BUS_RDATA,
        s_axi_HLS_LINEAR_PERIPH_BUS_RRESP,
        s_axi_HLS_LINEAR_PERIPH_BUS_BVALID,
        s_axi_HLS_LINEAR_PERIPH_BUS_BREADY,
        s_axi_HLS_LINEAR_PERIPH_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_S_AXI_HLS_LINEAR_PERIPH_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_HLS_LINEAR_PERIPH_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_HLS_LINEAR_PERIPH_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_HLS_LINEAR_PERIPH_BUS_AWVALID;
output   s_axi_HLS_LINEAR_PERIPH_BUS_AWREADY;
input  [C_S_AXI_HLS_LINEAR_PERIPH_BUS_ADDR_WIDTH - 1:0] s_axi_HLS_LINEAR_PERIPH_BUS_AWADDR;
input   s_axi_HLS_LINEAR_PERIPH_BUS_WVALID;
output   s_axi_HLS_LINEAR_PERIPH_BUS_WREADY;
input  [C_S_AXI_HLS_LINEAR_PERIPH_BUS_DATA_WIDTH - 1:0] s_axi_HLS_LINEAR_PERIPH_BUS_WDATA;
input  [C_S_AXI_HLS_LINEAR_PERIPH_BUS_WSTRB_WIDTH - 1:0] s_axi_HLS_LINEAR_PERIPH_BUS_WSTRB;
input   s_axi_HLS_LINEAR_PERIPH_BUS_ARVALID;
output   s_axi_HLS_LINEAR_PERIPH_BUS_ARREADY;
input  [C_S_AXI_HLS_LINEAR_PERIPH_BUS_ADDR_WIDTH - 1:0] s_axi_HLS_LINEAR_PERIPH_BUS_ARADDR;
output   s_axi_HLS_LINEAR_PERIPH_BUS_RVALID;
input   s_axi_HLS_LINEAR_PERIPH_BUS_RREADY;
output  [C_S_AXI_HLS_LINEAR_PERIPH_BUS_DATA_WIDTH - 1:0] s_axi_HLS_LINEAR_PERIPH_BUS_RDATA;
output  [1:0] s_axi_HLS_LINEAR_PERIPH_BUS_RRESP;
output   s_axi_HLS_LINEAR_PERIPH_BUS_BVALID;
input   s_axi_HLS_LINEAR_PERIPH_BUS_BREADY;
output  [1:0] s_axi_HLS_LINEAR_PERIPH_BUS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire  signed [31:0] x;
wire  signed [31:0] m;
wire   [31:0] c;
wire   [31:0] y;
reg    y_ap_vld;
reg    done_ap_vld;
reg   [31:0] c_read_reg_94;
wire   [31:0] grp_fu_83_p2;
reg   [31:0] mul_ln18_reg_109;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
end

linear_model_HLS_LINEAR_PERIPH_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_HLS_LINEAR_PERIPH_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_HLS_LINEAR_PERIPH_BUS_DATA_WIDTH ))
HLS_LINEAR_PERIPH_BUS_s_axi_U(
    .AWVALID(s_axi_HLS_LINEAR_PERIPH_BUS_AWVALID),
    .AWREADY(s_axi_HLS_LINEAR_PERIPH_BUS_AWREADY),
    .AWADDR(s_axi_HLS_LINEAR_PERIPH_BUS_AWADDR),
    .WVALID(s_axi_HLS_LINEAR_PERIPH_BUS_WVALID),
    .WREADY(s_axi_HLS_LINEAR_PERIPH_BUS_WREADY),
    .WDATA(s_axi_HLS_LINEAR_PERIPH_BUS_WDATA),
    .WSTRB(s_axi_HLS_LINEAR_PERIPH_BUS_WSTRB),
    .ARVALID(s_axi_HLS_LINEAR_PERIPH_BUS_ARVALID),
    .ARREADY(s_axi_HLS_LINEAR_PERIPH_BUS_ARREADY),
    .ARADDR(s_axi_HLS_LINEAR_PERIPH_BUS_ARADDR),
    .RVALID(s_axi_HLS_LINEAR_PERIPH_BUS_RVALID),
    .RREADY(s_axi_HLS_LINEAR_PERIPH_BUS_RREADY),
    .RDATA(s_axi_HLS_LINEAR_PERIPH_BUS_RDATA),
    .RRESP(s_axi_HLS_LINEAR_PERIPH_BUS_RRESP),
    .BVALID(s_axi_HLS_LINEAR_PERIPH_BUS_BVALID),
    .BREADY(s_axi_HLS_LINEAR_PERIPH_BUS_BREADY),
    .BRESP(s_axi_HLS_LINEAR_PERIPH_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .x(x),
    .m(m),
    .c(c),
    .y(y),
    .y_ap_vld(y_ap_vld),
    .done(16'd1),
    .done_ap_vld(done_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

linear_model_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(m),
    .din1(x),
    .ce(1'b1),
    .dout(grp_fu_83_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        c_read_reg_94 <= c;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mul_ln18_reg_109 <= grp_fu_83_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        done_ap_vld = 1'b1;
    end else begin
        done_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign y = (mul_ln18_reg_109 + c_read_reg_94);

endmodule //linear_model
